### ISSUE TITLE
Screen blanks when app lock fingerprint screen shows

### ISSUE THREAD

**Issue by liu-shuyuan** [okitavera/android_kernel_xiaomi_sdm710#1]
Fingerprint unlocking works fine. However, whenever the App Lock fingerprint screen comes up, the entire screen turns black. Touching the fingerprint sensor area results immediately in a vibration, the same as the one when fingerprint verification fails. Everything is normal again after pressing the power button twice, turning "off" and the screen and back on again.

**Comment by okitavera** [comment]
Mine is working perfectly 🤔

Did you already report to Xiaomi ? Since they're the one who upload the fingerprint driver, I'm 100% sure that they changed the drivers and needs an source updates to get a fully working on the latest miui.

**Comment by liu-shuyuan** [comment]
That's strange... I have not reported to Xiaomi yet, as I suspected this problem is caused by the kernel. But I'm on MIUI 10 9.7.4 developer version. Is that relevant?

**Comment by okitavera** [comment]
Oh you're on dev 9.7.4 ?

I'm still on dev 9.6.27.
And well, the `dsi-panel.c` is already buggy, it cannot correctly restore the brightness which causes to maxed out the brightness everytime I unlock the devices via fingerprint.

But App Lock is still working perfectly without any issues though.

Definitely, it's time to XiaoMi for an source code update, but I'm not sure if they would update it 🤷
